FROM docker.io/ubuntu

RUN apt-get update
RUN apt-get install git -y
RUN git clone https://github.com/doomguy-369/badCopyOfLazyScript
RUN git clone https://github.com/doomguy-369/apacheWheeleChair
RUN git clone https://github.com/doomguy-369/getInfo
